# Generated by Django 4.1 on 2026-06-24 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('biografia', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'autor',
            },
        ),
        migrations.CreateModel(
            name='EixoTecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'eixo',
            },
        ),
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('id_fk_autor', models.ForeignKey(db_column='id_fk_autor', on_delete=django.db.models.deletion.CASCADE, to='motorartigos.autor')),
                ('id_fk_eixo', models.ForeignKey(db_column='id_fk_eixo', on_delete=django.db.models.deletion.CASCADE, to='motorartigos.eixotecnologia')),
            ],
            options={
                'db_table': 'artigo',
            },
        ),
    ]
