# Generated by Django 4.2 on 2026-08-20 21:26

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EixoTecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Eixo de Tecnologia',
                'verbose_name_plural': 'Eixos de Tecnologia',
                'db_table': 'eixo',
            },
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('biografia', models.TextField(verbose_name='Biografia')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'db_table': 'autor',
            },
        ),
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Sem título', max_length=200, verbose_name='Título')),
                ('foto', models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/')),
                ('publicada', models.BooleanField(default=False)),
                ('nivel', models.CharField(choices=[('bo', 'box'), ('ru', 'rua'), ('mi', 'minishopping'), ('ga', 'galpão'), ('lo', 'loja de fachada'), ('gal', 'galeria de rua'), ('ba', 'banca'), ('co', 'corredor'), ('ca', 'calçada')], default='bo', max_length=3, verbose_name='Nível')),
                ('texto', tinymce.models.HTMLField(verbose_name='Texto')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Publicação')),
                ('id_fk_eixo', models.ForeignKey(db_column='id_fk_eixo', on_delete=django.db.models.deletion.CASCADE, related_name='artigos', to='motorartigos.eixotecnologia', verbose_name='Eixo')),
                ('id_fk_responsavel', models.ForeignKey(db_column='id_fk_responsavel', on_delete=django.db.models.deletion.CASCADE, related_name='artigos', to='motorartigos.responsavel', verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Artigo',
                'verbose_name_plural': 'Artigos',
                'db_table': 'artigo',
                'ordering': ['-data_publicacao'],
            },
        ),
    ]
