# Generated by Django 4.2 on 2026-08-20 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motorartigos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='responsavel',
            options={'verbose_name': 'Responsável', 'verbose_name_plural': 'Responsáveis'},
        ),
        migrations.AlterModelTable(
            name='responsavel',
            table='responsavel',
        ),
    ]
