# Generated by Django 4.2 on 2026-06-24 15:22

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('motorartigos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='texto',
            field=tinymce.models.HTMLField(),
        ),
    ]
