# Generated by Django 4.2 on 2026-08-21 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motorartigos', '0002_alter_responsavel_options_alter_responsavel_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artigo',
            new_name='Comercio',
        ),
        migrations.AlterModelOptions(
            name='comercio',
            options={'ordering': ['-data_publicacao'], 'verbose_name': 'Comercio', 'verbose_name_plural': 'Comercios'},
        ),
        migrations.AlterModelTable(
            name='comercio',
            table='comercio',
        ),
    ]
