# Generated by Django 4.2 on 2026-06-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorartigos', '0002_alter_artigo_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='nivel',
            field=models.CharField(choices=[('B', 'Básico'), ('I', 'Intermediário'), ('A', 'Avançado')], default='', max_length=50),
        ),
    ]
