# Generated by Django 4.2 on 2026-06-25 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motorartigos', '0003_artigo_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='id_fk_autor',
            field=models.ForeignKey(db_column='id_fk_autor', on_delete=django.db.models.deletion.CASCADE, to='motorartigos.autor', verbose_name='autor'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='id_fk_eixo',
            field=models.ForeignKey(db_column='id_fk_eixo', on_delete=django.db.models.deletion.CASCADE, to='motorartigos.eixotecnologia', verbose_name='autor'),
        ),
    ]
