# Generated by Django 4.2 on 2026-06-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorartigos', '0005_alter_artigo_options_alter_autor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='titulo',
            field=models.CharField(default='Sem título', max_length=200, verbose_name='Título'),
        ),
    ]
